spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobiauto
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            format_sql: true