spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobiauto
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            format_sql: true
jwt:
  secret: "mobiauto-secret-key-1234567890-abcdefghijklmnopqrstuvwxyz1234567890-abc" # 66 caracteres
  expiration: 86400000 # 24 horas