spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobiauto
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            format_sql: true
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
logging:
  level:
    root: INFO # Define o nível global do sistema
    com.mobiauto.backend: DEBUG # Nível específico para as classes
